apiVersion: v1
kind: Namespace
metadata:
  name: my-website
  labels:
    name: my-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
  namespace: my-website
spec:
  selector:
    matchLabels:
      app: my-website
  replicas: 2
  template:
    metadata:
      labels:
        app: my-website

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-website
  namespace: my-website
  labels:
    app: my-website
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: my-website